# Generated by Django 4.2.11 on 2024-04-01 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catigories',
            table='category',
        ),
    ]
